BEGIN;

INSERT INTO "Region" ("Nombre") VALUES
    ('Northern America'),
    ('Latin America'),
    ('Western Europe'),
    ('Eastern Europe'),
    ('Northern Africa'),
    ('Sub-Saharan Africa'),
    ('Middle East'),
    ('Asia Pacific'),
    ('South Asia'),
    ('East Asia')
ON CONFLICT ("Nombre") DO NOTHING;

INSERT INTO "Pais" ("Nombre", "ISO3", "Id_Region")
SELECT v.nombre, v.iso3, r."Id"
FROM (VALUES
    ('United States',                                         'USA', 'Northern America'),
    ('Canada',                                                'CAN', 'Northern America'),
    ('Bermuda',                                               'BMU', 'Northern America'),
    ('Anguilla',                                              'AIA', 'Latin America'),
    ('Antigua and Barbuda',                                   'ATG', 'Latin America'),
    ('Argentina',                                             'ARG', 'Latin America'),
    ('Aruba',                                                 'ABW', 'Latin America'),
    ('Bahamas',                                               'BHS', 'Latin America'),
    ('Barbados',                                              'BRB', 'Latin America'),
    ('Belize',                                                'BLZ', 'Latin America'),
    ('Bolivia',                                               'BOL', 'Latin America'),
    ('Brazil',                                                'BRA', 'Latin America'),
    ('British Virgin Islands',                                'VGB', 'Latin America'),
    ('Cayman Islands',                                        'CYM', 'Latin America'),
    ('Chile',                                                 'CHL', 'Latin America'),
    ('Colombia',                                              'COL', 'Latin America'),
    ('Costa Rica',                                            'CRI', 'Latin America'),
    ('Cuba',                                                  'CUB', 'Latin America'),
    ('Curacao',                                               'CUW', 'Latin America'),
    ('Dominican Republic',                                    'DOM', 'Latin America'),
    ('Ecuador',                                               'ECU', 'Latin America'),
    ('El Salvador',                                           'SLV', 'Latin America'),
    ('Falkland Islands (Malvinas)',                           'FLK', 'Latin America'),
    ('Grenada',                                               'GRD', 'Latin America'),
    ('Guatemala',                                             'GTM', 'Latin America'),
    ('Guyana',                                                'GUY', 'Latin America'),
    ('Haiti',                                                 'HTI', 'Latin America'),
    ('Honduras',                                              'HND', 'Latin America'),
    ('Jamaica',                                               'JAM', 'Latin America'),
    ('Mexico',                                                'MEX', 'Latin America'),
    ('Nicaragua',                                             'NIC', 'Latin America'),
    ('Panama',                                                'PAN', 'Latin America'),
    ('Paraguay',                                              'PRY', 'Latin America'),
    ('Peru',                                                  'PER', 'Latin America'),
    ('Puerto Rico',                                           'PRI', 'Latin America'),
    ('Saint Kitts and Nevis',                                 'KNA', 'Latin America'),
    ('Saint Lucia',                                           'LCA', 'Latin America'),
    ('Saint Martin (French part)',                            'MAF', 'Latin America'),
    ('Saint Pierre and Miquelon',                             'SPM', 'Latin America'),
    ('Saint Vincent and the Grenadines',                      'VCT', 'Latin America'),
    ('Sint Maarten',                                          'SXM', 'Latin America'),
    ('Suriname',                                              'SUR', 'Latin America'),
    ('Trinidad and Tobago',                                   'TTO', 'Latin America'),
    ('Uruguay',                                               'URY', 'Latin America'),
    ('Venezuela (Bolivarian Republic of)',                    'VEN', 'Latin America'),
    ('Andorra',                                               'AND', 'Western Europe'),
    ('Austria',                                               'AUT', 'Western Europe'),
    ('Belgium',                                               'BEL', 'Western Europe'),
    ('Cyprus',                                                'CYP', 'Western Europe'),
    ('Denmark',                                               'DNK', 'Western Europe'),
    ('Faroe Islands',                                         'FRO', 'Western Europe'),
    ('Finland',                                               'FIN', 'Western Europe'),
    ('France',                                                'FRA', 'Western Europe'),
    ('Germany',                                               'DEU', 'Western Europe'),
    ('Gibraltar',                                             'GIB', 'Western Europe'),
    ('Greece',                                                'GRC', 'Western Europe'),
    ('Greenland',                                             'GRL', 'Western Europe'),
    ('Guernsey',                                              'GGY', 'Western Europe'),
    ('Iceland',                                               'ISL', 'Western Europe'),
    ('Ireland',                                               'IRL', 'Western Europe'),
    ('Isle of Man',                                           'IMN', 'Western Europe'),
    ('Italy',                                                 'ITA', 'Western Europe'),
    ('Jersey',                                                'JEY', 'Western Europe'),
    ('Liechtenstein',                                         'LIE', 'Western Europe'),
    ('Luxembourg',                                            'LUX', 'Western Europe'),
    ('Malta',                                                 'MLT', 'Western Europe'),
    ('Monaco',                                                'MCO', 'Western Europe'),
    ('Netherlands',                                           'NLD', 'Western Europe'),
    ('Norway',                                                'NOR', 'Western Europe'),
    ('Portugal',                                              'PRT', 'Western Europe'),
    ('San Marino',                                            'SMR', 'Western Europe'),
    ('Spain',                                                 'ESP', 'Western Europe'),
    ('Sweden',                                                'SWE', 'Western Europe'),
    ('Switzerland',                                           'CHE', 'Western Europe'),
    ('United Kingdom of Great Britain and Northern Ireland',  'GBR', 'Western Europe'),
    ('Albania',                                               'ALB', 'Eastern Europe'),
    ('Armenia',                                               'ARM', 'Eastern Europe'),
    ('Azerbaijan',                                            'AZE', 'Eastern Europe'),
    ('Belarus',                                               'BLR', 'Eastern Europe'),
    ('Bosnia and Herzegovina',                                'BIH', 'Eastern Europe'),
    ('Bulgaria',                                              'BGR', 'Eastern Europe'),
    ('Croatia',                                               'HRV', 'Eastern Europe'),
    ('Czechia',                                               'CZE', 'Eastern Europe'),
    ('Estonia',                                               'EST', 'Eastern Europe'),
    ('Georgia',                                               'GEO', 'Eastern Europe'),
    ('Hungary',                                               'HUN', 'Eastern Europe'),
    ('Kazakhstan',                                            'KAZ', 'Eastern Europe'),
    ('Kosovo',                                                'XKX', 'Eastern Europe'),
    ('Kyrgyzstan',                                            'KGZ', 'Eastern Europe'),
    ('Latvia',                                                'LVA', 'Eastern Europe'),
    ('Lithuania',                                             'LTU', 'Eastern Europe'),
    ('Moldova (Republic of)',                                 'MDA', 'Eastern Europe'),
    ('Montenegro',                                            'MNE', 'Eastern Europe'),
    ('North Macedonia',                                       'MKD', 'Eastern Europe'),
    ('Poland',                                                'POL', 'Eastern Europe'),
    ('Romania',                                               'ROU', 'Eastern Europe'),
    ('Russian Federation',                                    'RUS', 'Eastern Europe'),
    ('Serbia',                                                'SRB', 'Eastern Europe'),
    ('Slovakia',                                              'SVK', 'Eastern Europe'),
    ('Slovenia',                                              'SVN', 'Eastern Europe'),
    ('Tajikistan',                                            'TJK', 'Eastern Europe'),
    ('Turkmenistan',                                          'TKM', 'Eastern Europe'),
    ('Ukraine',                                               'UKR', 'Eastern Europe'),
    ('Uzbekistan',                                            'UZB', 'Eastern Europe'),
    ('Algeria',                                               'DZA', 'Northern Africa'),
    ('Egypt',                                                 'EGY', 'Northern Africa'),
    ('Libya',                                                 'LBY', 'Northern Africa'),
    ('Morocco',                                               'MAR', 'Northern Africa'),
    ('Sudan',                                                 'SDN', 'Northern Africa'),
    ('Tunisia',                                               'TUN', 'Northern Africa'),
    ('Angola',                                                'AGO', 'Sub-Saharan Africa'),
    ('Benin',                                                 'BEN', 'Sub-Saharan Africa'),
    ('Botswana',                                              'BWA', 'Sub-Saharan Africa'),
    ('Burkina Faso',                                          'BFA', 'Sub-Saharan Africa'),
    ('Burundi',                                               'BDI', 'Sub-Saharan Africa'),
    ('Cabo Verde',                                            'CPV', 'Sub-Saharan Africa'),
    ('Cameroon',                                              'CMR', 'Sub-Saharan Africa'),
    ('Central African Republic',                              'CAF', 'Sub-Saharan Africa'),
    ('Chad',                                                  'TCD', 'Sub-Saharan Africa'),
    ('Comoros',                                               'COM', 'Sub-Saharan Africa'),
    ('Congo Democratic Republic of the',                      'COD', 'Sub-Saharan Africa'),
    ('Cote d''Ivoire',                                        'CIV', 'Sub-Saharan Africa'),
    ('Djibouti',                                              'DJI', 'Sub-Saharan Africa'),
    ('Ethiopia',                                              'ETH', 'Sub-Saharan Africa'),
    ('Gabon',                                                 'GAB', 'Sub-Saharan Africa'),
    ('Gambia',                                                'GMB', 'Sub-Saharan Africa'),
    ('Ghana',                                                 'GHA', 'Sub-Saharan Africa'),
    ('Guinea',                                                'GIN', 'Sub-Saharan Africa'),
    ('Guinea-Bissau',                                         'GNB', 'Sub-Saharan Africa'),
    ('Kenya',                                                 'KEN', 'Sub-Saharan Africa'),
    ('Lesotho',                                               'LSO', 'Sub-Saharan Africa'),
    ('Liberia',                                               'LBR', 'Sub-Saharan Africa'),
    ('Madagascar',                                            'MDG', 'Sub-Saharan Africa'),
    ('Malawi',                                                'MWI', 'Sub-Saharan Africa'),
    ('Mali',                                                  'MLI', 'Sub-Saharan Africa'),
    ('Mauritania',                                            'MRT', 'Sub-Saharan Africa'),
    ('Mauritius',                                             'MUS', 'Sub-Saharan Africa'),
    ('Mozambique',                                            'MOZ', 'Sub-Saharan Africa'),
    ('Namibia',                                               'NAM', 'Sub-Saharan Africa'),
    ('Niger',                                                 'NER', 'Sub-Saharan Africa'),
    ('Nigeria',                                               'NGA', 'Sub-Saharan Africa'),
    ('Rwanda',                                                'RWA', 'Sub-Saharan Africa'),
    ('Sao Tome and Principe',                                 'STP', 'Sub-Saharan Africa'),
    ('Senegal',                                               'SEN', 'Sub-Saharan Africa'),
    ('Seychelles',                                            'SYC', 'Sub-Saharan Africa'),
    ('Sierra Leone',                                          'SLE', 'Sub-Saharan Africa'),
    ('Somalia',                                               'SOM', 'Sub-Saharan Africa'),
    ('South Africa',                                          'ZAF', 'Sub-Saharan Africa'),
    ('South Sudan',                                           'SSD', 'Sub-Saharan Africa'),
    ('Eswatini',                                              'SWZ', 'Sub-Saharan Africa'),
    ('Tanzania, United Republic of',                          'TZA', 'Sub-Saharan Africa'),
    ('Togo',                                                  'TGO', 'Sub-Saharan Africa'),
    ('Uganda',                                                'UGA', 'Sub-Saharan Africa'),
    ('Zambia',                                                'ZMB', 'Sub-Saharan Africa'),
    ('Zimbabwe',                                              'ZWE', 'Sub-Saharan Africa'),
    ('Bahrain',                                               'BHR', 'Middle East'),
    ('Iran (Islamic Republic of)',                            'IRN', 'Middle East'),
    ('Iraq',                                                  'IRQ', 'Middle East'),
    ('Israel',                                                'ISR', 'Middle East'),
    ('Jordan',                                                'JOR', 'Middle East'),
    ('Kuwait',                                                'KWT', 'Middle East'),
    ('Lebanon',                                               'LBN', 'Middle East'),
    ('Oman',                                                  'OMN', 'Middle East'),
    ('Palestine, State of',                                   'WBG', 'Middle East'),
    ('Qatar',                                                 'QAT', 'Middle East'),
    ('Saudi Arabia',                                          'SAU', 'Middle East'),
    ('Syrian Arab Republic',                                  'SYR', 'Middle East'),
    ('Turkey',                                                'TUR', 'Middle East'),
    ('United Arab Emirates',                                  'ARE', 'Middle East'),
    ('Yemen',                                                 'YEM', 'Middle East'),
    ('American Samoa',                                        'ASM', 'Asia Pacific'),
    ('Australia',                                             'AUS', 'Asia Pacific'),
    ('Brunei Darussalam',                                     'BRN', 'Asia Pacific'),
    ('Cambodia',                                              'KHM', 'Asia Pacific'),
    ('Cook Islands',                                          'COK', 'Asia Pacific'),
    ('Fiji',                                                  'FJI', 'Asia Pacific'),
    ('French Polynesia',                                      'PYF', 'Asia Pacific'),
    ('Guam',                                                  'GUM', 'Asia Pacific'),
    ('Hong Kong',                                             'HKG', 'Asia Pacific'),
    ('Indonesia',                                             'IDN', 'Asia Pacific'),
    ('Japan',                                                 'JPN', 'Asia Pacific'),
    ('Kiribati',                                              'KIR', 'Asia Pacific'),
    ('South Korea',                                           'KOR', 'Asia Pacific'),
    ('Lao People''s Democratic Republic',                     'LAO', 'Asia Pacific'),
    ('Macao',                                                 'MAC', 'Asia Pacific'),
    ('Malaysia',                                              'MYS', 'Asia Pacific'),
    ('Marshall Islands',                                      'MHL', 'Asia Pacific'),
    ('Micronesia (Federated States of)',                      'FSM', 'Asia Pacific'),
    ('New Caledonia',                                         'NCL', 'Asia Pacific'),
    ('New Zealand',                                           'NZL', 'Asia Pacific'),
    ('Niue',                                                  'NIU', 'Asia Pacific'),
    ('Northern Mariana Islands',                              'MNP', 'Asia Pacific'),
    ('Palau',                                                 'PLW', 'Asia Pacific'),
    ('Papua New Guinea',                                      'PNG', 'Asia Pacific'),
    ('Philippines',                                           'PHL', 'Asia Pacific'),
    ('Samoa',                                                 'WSM', 'Asia Pacific'),
    ('Singapore',                                             'SGP', 'Asia Pacific'),
    ('Solomon Islands',                                       'SLB', 'Asia Pacific'),
    ('Taiwan',                                                'TWN', 'Asia Pacific'),
    ('Thailand',                                              'THA', 'Asia Pacific'),
    ('Timor-Leste',                                           'TLS', 'Asia Pacific'),
    ('Tonga',                                                 'TON', 'Asia Pacific'),
    ('Tuvalu',                                                'TUV', 'Asia Pacific'),
    ('Vanuatu',                                               'VUT', 'Asia Pacific'),
    ('Viet Nam',                                              'VNM', 'Asia Pacific'),
    ('Afghanistan',                                           'AFG', 'South Asia'),
    ('Bangladesh',                                            'BGD', 'South Asia'),
    ('Bhutan',                                                'BTN', 'South Asia'),
    ('India',                                                 'IND', 'South Asia'),
    ('Maldives',                                              'MDV', 'South Asia'),
    ('Myanmar',                                               'MMR', 'South Asia'),
    ('Nepal',                                                 'NPL', 'South Asia'),
    ('Pakistan',                                              'PAK', 'South Asia'),
    ('Sri Lanka',                                             'LKA', 'South Asia'),
    ('China',                                                 'CHN', 'East Asia'),
    ('Mongolia',                                              'MNG', 'East Asia'),
    ('North Korea',                                           'PRK', 'East Asia'),
    ('Unknown',                                               NULL,  NULL)
) AS v(nombre, iso3, region_name)
LEFT JOIN "Region" r ON r."Nombre" = v.region_name
ON CONFLICT ("Nombre") DO NOTHING;

INSERT INTO "Area" ("Nombre") VALUES
    ('CS'),
    ('BIO'),
    ('CHEM'),
    ('EARTH'),
    ('PHYS')
ON CONFLICT ("Nombre") DO NOTHING;

INSERT INTO "Posicion" ("PosicionInteres") VALUES
    ('first'),
    ('second'),
    ('penultimate'),
    ('last'),
    ('other')
ON CONFLICT ("PosicionInteres") DO NOTHING;

COMMIT;
